{{define "file"}}// Code generated by graftgen{{if .Version}} (version {{.Version}}){{end}}; DO NOT EDIT.

// Source interfaces: {{.Source}}

{{- if .Command}}
// Command: {{.Command}}
{{- end}}

package {{.Package}}

{{if .NeedContext }}import "context"{{end}}

{{range .Helpers}}
{{template "helper" .}}
{{end}}
{{range .Interfaces}}
{{template "interface" .}}
{{end}}
{{end}}
