{{define "file"}}// Code generated by graftgen; DO NOT EDIT.
// Source: {{.Source}}
package {{.Package}}

{{if .NeedContext }}import "context"{{end}}

{{range .Helpers}}
{{template "helper" .}}
{{end}}
{{range .Interfaces}}
{{template "interface" .}}
{{end}}
{{end}}
