// Code generated by graftgen (version devel); DO NOT EDIT.

// Source interfaces: Builder
// Command: graftgen -interface=Builder -output=graft_gen.go

package mapsrc

// map_28faf228d970 maps a value of type Input to Output.
func map_28faf228d970(in Input) Output {
	// Destination zero value; fields populated by node sequence below.
	var dst Output
	dst.UserName = in.P.Name
	dst.Code = in.P.Detail.Code
	dst.Label = in.Label
	return dst
}

// builderImpl is the generated implementation of Builder.
type builderImpl struct{}

// NewBuilder returns a new Builder implementation.
func NewBuilder() Builder { return &builderImpl{} }

// Build maps p0 to the destination type.
func (m *builderImpl) Build(p0 Input) Output {
	return map_28faf228d970(p0)
}
