// Code generated by graftgen (version devel); DO NOT EDIT.

// Source interfaces: CtxMapper
// Command: graftgen -interface=CtxMapper -output=graft_gen.go

package ctxex

import "context"

// ctxMapperImpl is the generated implementation of CtxMapper.
type ctxMapperImpl struct{}

// NewCtxMapper returns a new CtxMapper implementation.
func NewCtxMapper() CtxMapper { return &ctxMapperImpl{} }

// Map maps p0 to the destination type.
func (m *ctxMapperImpl) Map(ctx context.Context, p0 In) Out {
	var dst Out
	dst.V = p0.V
	return dst
}

// MapNamedCtx maps in to the destination type.
func (m *ctxMapperImpl) MapNamedCtx(c context.Context, in In) Out {
	var dst Out
	dst.V = in.V
	return dst
}
