// Code generated by graftgen; DO NOT EDIT.
// Source: CtxMapper
package ctxex

import "context"

// ctxMapperImpl is the generated implementation of CtxMapper.
type ctxMapperImpl struct{}

// NewCtxMapper returns a new CtxMapper implementation.
func NewCtxMapper() CtxMapper { return &ctxMapperImpl{} }

// Map maps p1 to the destination type.
func (m *ctxMapperImpl) Map(p0 context.Context, p1 In) Out {
	var dst Out
	dst.V = p1.V
	return dst
}
