// Code generated by graftgen (version devel); DO NOT EDIT.

// Source interfaces: Composer
// Command: graftgen -interface=Composer -output=graft_gen.go

package mapsrc_index

import "context"

// composerImpl is the generated implementation of Composer.
type composerImpl struct{}

// NewComposer returns a new Composer implementation.
func NewComposer() Composer { return &composerImpl{} }

// Compose maps a to the destination type.
func (m *composerImpl) Compose(a A, b B) Out {
	var dst Out
	dst.FromA = a.ValueA
	dst.FromB = b.ValueB
	dst.Common = a.Common
	return dst
}

// ComposeIdx maps p0 to the destination type.
func (m *composerImpl) ComposeIdx(p0 A, p1 B) OutIdx {
	var dst OutIdx
	dst.FromA = p0.ValueA
	dst.FromB = p1.ValueB
	dst.Common = p0.Common
	return dst
}

// ComposeIdxContext maps p0 to the destination type.
func (m *composerImpl) ComposeIdxContext(ctx context.Context, p0 A, p1 B) OutIdx {
	var dst OutIdx
	dst.FromA = p0.ValueA
	dst.FromB = p1.ValueB
	dst.Common = p0.Common
	return dst
}
