// Code generated by graftgen; DO NOT EDIT.
// Source: AddressMapper, UserMapper
package basic

// Helper: map_a80deba95087
func map_a80deba95087(in Address) AddressDTO {
	// Destination zero value; fields populated by node sequence below.
	var dst AddressDTO
	// node START H0.0 kind=assignDirect
	dst.Street = in.Street // node END H0.0
	// node START H0.1 kind=assignDirect
	dst.City = in.City // node END H0.1
	return dst
}

// Helper: map_c2b1489071c3
func map_c2b1489071c3(in User) UserDTO {
	// Destination zero value; fields populated by node sequence below.
	var dst UserDTO
	// node START H1.0 kind=assignDirect
	dst.ID = in.ID // node END H1.0
	// node START H1.1 kind=assignDirect
	dst.Name = in.Name // node END H1.1
	// node START H1.2 kind=assignHelper
	dst.Addr = map_a80deba95087(in.Addr)
	// node END H1.2
	return dst
}

// addressMapperImpl is the generated implementation of AddressMapper.
type addressMapperImpl struct{}

// NewAddressMapper returns a new AddressMapper implementation.
func NewAddressMapper() AddressMapper { return &addressMapperImpl{} }

// AddressToDTO maps p0 to the destination type.
func (m *addressMapperImpl) AddressToDTO(p0 Address) AddressDTO {
	// node START I0.M0.0 kind=return
	return map_a80deba95087(p0) // node END I0.M0.0
}

// userMapperImpl is the generated implementation of UserMapper.
type userMapperImpl struct{}

// NewUserMapper returns a new UserMapper implementation.
func NewUserMapper() UserMapper { return &userMapperImpl{} }

// UserToDTO maps p0 to the destination type.
func (m *userMapperImpl) UserToDTO(p0 User) UserDTO {
	// node START I1.M0.0 kind=return
	return map_c2b1489071c3(p0) // node END I1.M0.0
}
