// Code generated by graftgen (version devel); DO NOT EDIT.

// Source interfaces: AddressMapper, UserMapper
// Command: graftgen -interface=UserMapper,AddressMapper -output=graft_gen.go

package nested

// map_Address_to_AddressDTO maps a value of type Address to AddressDTO.
func map_Address_to_AddressDTO(in Address) AddressDTO {
	// Destination zero value; fields populated by node sequence below.
	var dst AddressDTO
	dst.Street = in.Street
	dst.City = in.City
	return dst
}

// map_User_to_UserDTO maps a value of type User to UserDTO.
func map_User_to_UserDTO(in User) UserDTO {
	// Destination zero value; fields populated by node sequence below.
	var dst UserDTO
	dst.ID = in.ID
	dst.Name = in.Name
	dst.Addr = map_Address_to_AddressDTO(in.Addr)

	return dst
}

// addressMapperImpl is the generated implementation of AddressMapper.
type addressMapperImpl struct{}

// NewAddressMapper returns a new AddressMapper implementation.
func NewAddressMapper() AddressMapper { return &addressMapperImpl{} }

// AddressToDTO maps p0 to the destination type.
func (m *addressMapperImpl) AddressToDTO(p0 Address) AddressDTO {
	return map_Address_to_AddressDTO(p0)
}

// userMapperImpl is the generated implementation of UserMapper.
type userMapperImpl struct{}

// NewUserMapper returns a new UserMapper implementation.
func NewUserMapper() UserMapper { return &userMapperImpl{} }

// UserToDTO maps p0 to the destination type.
func (m *userMapperImpl) UserToDTO(p0 User) UserDTO {
	return map_User_to_UserDTO(p0)
}
