// Code generated by graftgen (version devel); DO NOT EDIT.

// Source interfaces: AddressMapper, UserMapper
// Command: graftgen -interface=UserMapper,AddressMapper -output=graft_gen.go -custom_funcs=

package basic

// Helper: map_a80deba95087
func map_a80deba95087(in Address) AddressDTO {
	// Destination zero value; fields populated by node sequence below.
	var dst AddressDTO
	dst.Street = in.Street
	dst.City = in.City
	return dst
}

// Helper: map_c2b1489071c3
func map_c2b1489071c3(in User) UserDTO {
	// Destination zero value; fields populated by node sequence below.
	var dst UserDTO
	dst.ID = in.ID
	dst.Name = in.Name
	dst.Addr = map_a80deba95087(in.Addr)

	return dst
}

// addressMapperImpl is the generated implementation of AddressMapper.
type addressMapperImpl struct{}

// NewAddressMapper returns a new AddressMapper implementation.
func NewAddressMapper() AddressMapper { return &addressMapperImpl{} }

// AddressToDTO maps p0 to the destination type.
func (m *addressMapperImpl) AddressToDTO(p0 Address) AddressDTO {
	return map_a80deba95087(p0)
}

// userMapperImpl is the generated implementation of UserMapper.
type userMapperImpl struct{}

// NewUserMapper returns a new UserMapper implementation.
func NewUserMapper() UserMapper { return &userMapperImpl{} }

// UserToDTO maps p0 to the destination type.
func (m *userMapperImpl) UserToDTO(p0 User) UserDTO {
	return map_c2b1489071c3(p0)
}
