// Code generated by graftgen (version devel); DO NOT EDIT.

// Source interfaces: Mapper
// Command: graftgen -interface=Mapper -output=graft_gen.go -custom_funcs=

package error_propagation

// Helper: map_28faf228d970
func map_28faf228d970(in Input) (Output, error) {
	// Destination zero value; fields populated by node sequence below.
	var dst Output
	if in.Items != nil {
		dst.Items = make([]ItemDTO, len(in.Items))
		for i, v := range in.Items { // v used by child nodes
			var mapped ItemDTO
			tmp, err := ItemToDTO(v)
			if err != nil {
				return dst, err
			}
			mapped = tmp

			dst.Items[i] = mapped
		}
	} else {
		dst.Items = nil
	}
	return dst, nil
}

// mapperImpl is the generated implementation of Mapper.
type mapperImpl struct{}

// NewMapper returns a new Mapper implementation.
func NewMapper() Mapper { return &mapperImpl{} }

// Map maps p0 to the destination type.
func (m *mapperImpl) Map(p0 Input) (Output, error) {
	return map_28faf228d970(p0)
}
