// Code generated by graftgen (version devel); DO NOT EDIT.

// Source interfaces: Mapper
// Command: graftgen -interface=Mapper -output=graft_gen.go -custom_funcs=

package custom_function

// Helper: map_09a6260f7c56
func map_09a6260f7c56(in A) B {
	// Destination zero value; fields populated by node sequence below.
	var dst B
	dst.N = in.N
	return dst
}

// mapperImpl is the generated implementation of Mapper.
type mapperImpl struct{}

// NewMapper returns a new Mapper implementation.
func NewMapper() Mapper { return &mapperImpl{} }

// Map maps a to the destination type.
func (m *mapperImpl) Map(a A) B {
	return map_09a6260f7c56(a)
}

// MapErr maps a to the destination type.
func (m *mapperImpl) MapErr(a A) (B, error) {
	return map_09a6260f7c56(a), nil
}
