// Code generated by graftgen; DO NOT EDIT.
// Source: RecMapper
package recursive

// Helper: map_09a6260f7c56
func map_09a6260f7c56(in A) B {
	// Destination zero value; fields populated by node sequence below.
	var dst B
	dst.Text = in.Text
	// no source field for A
	return dst
}

// recMapperImpl is the generated implementation of RecMapper.
type recMapperImpl struct{}

// NewRecMapper returns a new RecMapper implementation.
func NewRecMapper() RecMapper { return &recMapperImpl{} }

// AToB maps p0 to the destination type.
func (m *recMapperImpl) AToB(p0 A) B {
	return map_09a6260f7c56(p0)
}
