// Code generated by graftgen (version v0.0.0-20250825190222-52377a33b817+dirty); DO NOT EDIT.

// Source interfaces: RecMapper
// Command: graftgen -interface=RecMapper -output=graft_gen.go -custom_funcs=

package recursive

// map_09a6260f7c56 maps a value of type A to B.
func map_09a6260f7c56(in A) B {
	// Destination zero value; fields populated by node sequence below.
	var dst B
	dst.Text = in.Text
	// no source field for A
	return dst
}

// recMapperImpl is the generated implementation of RecMapper.
type recMapperImpl struct{}

// NewRecMapper returns a new RecMapper implementation.
func NewRecMapper() RecMapper { return &recMapperImpl{} }

// AToB maps p0 to the destination type.
func (m *recMapperImpl) AToB(p0 A) B {
	return map_09a6260f7c56(p0)
}
