// Code generated by graftgen; DO NOT EDIT.
// Source: Assembler
package multi_param

// assemblerImpl is the generated implementation of Assembler.
type assemblerImpl struct{}

// NewAssembler returns a new Assembler implementation.
func NewAssembler() Assembler { return &assemblerImpl{} }

// Assemble maps p0 to the destination type.
func (m *assemblerImpl) Assemble(p0 Core, p1 Meta) Combined {
	var dst Combined
	dst.ID = p0.ID
	dst.Name = p0.Name
	dst.Version = p1.Version
	return dst
}
