// Code generated by graftgen (version devel); DO NOT EDIT.

// Source interfaces: Assembler
// Command: graftgen -interface=Assembler -output=graft_gen.go

package multi_param

// assemblerImpl is the generated implementation of Assembler.
type assemblerImpl struct{}

// NewAssembler returns a new Assembler implementation.
func NewAssembler() Assembler { return &assemblerImpl{} }

// Assemble maps p0 to the destination type.
func (m *assemblerImpl) Assemble(p0 Core, p1 Meta) Combined {
	var dst Combined
	dst.ID = p0.ID
	dst.Name = p0.Name
	dst.Version = p1.Version
	return dst
}
