// Code generated by graftgen (version devel); DO NOT EDIT.

// Source interfaces: UserMapper
// Command: graftgen -interface=UserMapper -output=graft_gen.go

package ptr

// map_c2b1489071c3 maps a value of type User to UserDTO.
func map_c2b1489071c3(in User) UserDTO {
	// Destination zero value; fields populated by node sequence below.
	var dst UserDTO
	dst.ID = in.ID
	dst.Name = in.Name
	return dst
}

// map_fd87b162916e maps a value of type *User to UserDTO.
func map_fd87b162916e(in *User) UserDTO {
	if in == nil {
		return UserDTO{}
	}
	// Destination zero value; fields populated by node sequence below.
	var dst UserDTO
	dst.ID = in.ID
	dst.Name = in.Name
	return dst
}

// map_82ccc81fd210 maps a value of type *User to *UserDTO.
func map_82ccc81fd210(in *User) *UserDTO {
	if in == nil {
		return nil
	}
	// Allocate destination pointer
	dst := new(UserDTO)
	dst.ID = in.ID
	dst.Name = in.Name
	return dst
}

// map_168535d375f4 maps a value of type User to *UserDTO.
func map_168535d375f4(in User) *UserDTO {
	// Allocate destination pointer
	dst := new(UserDTO)
	dst.ID = in.ID
	dst.Name = in.Name
	return dst
}

// userMapperImpl is the generated implementation of UserMapper.
type userMapperImpl struct{}

// NewUserMapper returns a new UserMapper implementation.
func NewUserMapper() UserMapper { return &userMapperImpl{} }

// ToDTO maps p0 to the destination type.
func (m *userMapperImpl) ToDTO(p0 User) UserDTO {
	return map_c2b1489071c3(p0)
}

// ToDTOFromPtr maps p0 to the destination type.
func (m *userMapperImpl) ToDTOFromPtr(p0 *User) UserDTO {
	return map_fd87b162916e(p0)
}

// ToDTOPtr maps p0 to the destination type.
func (m *userMapperImpl) ToDTOPtr(p0 *User) *UserDTO {
	return map_82ccc81fd210(p0)
}

// ToDTOPtrFromVal maps p0 to the destination type.
func (m *userMapperImpl) ToDTOPtrFromVal(p0 User) *UserDTO {
	return map_168535d375f4(p0)
}
