// Code generated by graftgen; DO NOT EDIT.
// Source: ColMapper
package collections

// Helper: map_0662979fb6d6
func map_0662979fb6d6(in Elem) ElemDTO {
	// Destination zero value; fields populated by node sequence below.
	var dst ElemDTO
	dst.V = in.V
	return dst
}

// Helper: map_3f15186025aa
func map_3f15186025aa(in []Elem) []ElemDTO {
	// Destination zero value; fields populated by node sequence below.
	var dst []ElemDTO
	if in != nil {
		dst = make([]ElemDTO, len(in))
		for i, v := range in { // v used by child nodes
			var mapped ElemDTO
			mapped = map_0662979fb6d6(v)

			dst[i] = mapped
		}
	} else {
		dst = nil
	}
	return dst
}

// Helper: map_d0ac0bbc1462
func map_d0ac0bbc1462(in map[string]Elem) map[string]ElemDTO {
	// Destination zero value; fields populated by node sequence below.
	var dst map[string]ElemDTO
	if in != nil {
		dst = make(map[string]ElemDTO, len(in))
		for k, v := range in { // k,v used by child nodes
			var mapped ElemDTO
			mapped = map_0662979fb6d6(v)

			dst[k] = mapped
		}
	} else {
		dst = nil
	}
	return dst
}

// Helper: map_480c38455f38
func map_480c38455f38(in MapContainer) (MapContainerDTO, error) {
	// Destination zero value; fields populated by node sequence below.
	var dst MapContainerDTO
	if in.Items != nil {
		dst.Items = make(map[string]ElemDTO, len(in.Items))
		for k, v := range in.Items { // k,v used by child nodes
			var mapped ElemDTO
			tmp, err := ElemToElemDTO(v)
			if err != nil {
				return dst, err
			}
			mapped = tmp

			dst.Items[k] = mapped
		}
	} else {
		dst.Items = nil
	}
	return dst, nil
}

// Helper: map_652530217676
func map_652530217676(in SliceContainer) (SliceContainerDTO, error) {
	// Destination zero value; fields populated by node sequence below.
	var dst SliceContainerDTO
	if in.Items != nil {
		dst.Items = make([]ElemDTO, len(in.Items))
		for i, v := range in.Items { // v used by child nodes
			var mapped ElemDTO
			tmp, err := ElemToElemDTO(v)
			if err != nil {
				return dst, err
			}
			mapped = tmp

			dst.Items[i] = mapped
		}
	} else {
		dst.Items = nil
	}
	return dst, nil
}

// colMapperImpl is the generated implementation of ColMapper.
type colMapperImpl struct{}

// NewColMapper returns a new ColMapper implementation.
func NewColMapper() ColMapper { return &colMapperImpl{} }

// Map maps p0 to the destination type.
func (m *colMapperImpl) Map(p0 []Elem) ([]ElemDTO, error) {
	return map_3f15186025aa(p0), nil
}

// MapMap maps p0 to the destination type.
func (m *colMapperImpl) MapMap(p0 map[string]Elem) (map[string]ElemDTO, error) {
	return map_d0ac0bbc1462(p0), nil
}

// MapMapContainer maps p0 to the destination type.
func (m *colMapperImpl) MapMapContainer(p0 MapContainer) (MapContainerDTO, error) {
	return map_480c38455f38(p0)
}

// MapSliceContainer maps p0 to the destination type.
func (m *colMapperImpl) MapSliceContainer(p0 SliceContainer) (SliceContainerDTO, error) {
	return map_652530217676(p0)
}
