// Code generated by graftgen (version devel); DO NOT EDIT.

// Source interfaces: ColMapper
// Command: graftgen -interface=ColMapper -output=graft_gen.go

package collections

// mapc_Slice_Elem_to_Slice_ElemDTO maps a value of type []Elem to []ElemDTO.
func mapc_Slice_Elem_to_Slice_ElemDTO(in []Elem) ([]ElemDTO, error) {
	// Destination zero value; fields populated by node sequence below.
	var dst []ElemDTO
	if in != nil {
		dst = make([]ElemDTO, len(in))
		for i, v := range in { // v used by child nodes
			var mapped ElemDTO
			tmp, err := map_Elem_to_ElemDTO(v)
			if err != nil {
				return dst, err
			}
			mapped = tmp

			dst[i] = mapped
		}
	} else {
		dst = nil
	}
	return dst, nil
}

// mapc_Map_string_To_Elem_to_Map_string_To_ElemDTO maps a value of type map[string]Elem to map[string]ElemDTO.
func mapc_Map_string_To_Elem_to_Map_string_To_ElemDTO(in map[string]Elem) (map[string]ElemDTO, error) {
	// Destination zero value; fields populated by node sequence below.
	var dst map[string]ElemDTO
	if in != nil {
		dst = make(map[string]ElemDTO, len(in))
		for k, v := range in { // k,v used by child nodes
			var mapped ElemDTO
			tmp, err := map_Elem_to_ElemDTO(v)
			if err != nil {
				return dst, err
			}
			mapped = tmp

			dst[k] = mapped
		}
	} else {
		dst = nil
	}
	return dst, nil
}

// map_MapContainer_to_MapContainerDTO maps a value of type MapContainer to MapContainerDTO.
func map_MapContainer_to_MapContainerDTO(in MapContainer) (MapContainerDTO, error) {
	// Destination zero value; fields populated by node sequence below.
	var dst MapContainerDTO
	if in.Items != nil {
		dst.Items = make(map[string]ElemDTO, len(in.Items))
		for k, v := range in.Items { // k,v used by child nodes
			var mapped ElemDTO
			tmp, err := ElemToElemDTO(v)
			if err != nil {
				return dst, err
			}
			mapped = tmp

			dst.Items[k] = mapped
		}
	} else {
		dst.Items = nil
	}
	return dst, nil
}

// map_SliceContainer_to_SliceContainerDTO maps a value of type SliceContainer to SliceContainerDTO.
func map_SliceContainer_to_SliceContainerDTO(in SliceContainer) (SliceContainerDTO, error) {
	// Destination zero value; fields populated by node sequence below.
	var dst SliceContainerDTO
	if in.Items != nil {
		dst.Items = make([]ElemDTO, len(in.Items))
		for i, v := range in.Items { // v used by child nodes
			var mapped ElemDTO
			tmp, err := ElemToElemDTO(v)
			if err != nil {
				return dst, err
			}
			mapped = tmp

			dst.Items[i] = mapped
		}
	} else {
		dst.Items = nil
	}
	return dst, nil
}

// map_Elem_to_ElemDTO maps a value of type Elem to ElemDTO.
func map_Elem_to_ElemDTO(in Elem) (ElemDTO, error) {
	// Destination zero value; fields populated by node sequence below.
	var dst ElemDTO
	tmp, err := ElemToElemDTO(in)
	if err != nil {
		return dst, err
	}
	dst = tmp

	return dst, nil
}

// colMapperImpl is the generated implementation of ColMapper.
type colMapperImpl struct{}

// NewColMapper returns a new ColMapper implementation.
func NewColMapper() ColMapper { return &colMapperImpl{} }

// Map maps p0 to the destination type.
func (m *colMapperImpl) Map(p0 []Elem) ([]ElemDTO, error) {
	return mapc_Slice_Elem_to_Slice_ElemDTO(p0)
}

// MapMap maps p0 to the destination type.
func (m *colMapperImpl) MapMap(p0 map[string]Elem) (map[string]ElemDTO, error) {
	return mapc_Map_string_To_Elem_to_Map_string_To_ElemDTO(p0)
}

// MapMapContainer maps p0 to the destination type.
func (m *colMapperImpl) MapMapContainer(p0 MapContainer) (MapContainerDTO, error) {
	return map_MapContainer_to_MapContainerDTO(p0)
}

// MapSliceContainer maps p0 to the destination type.
func (m *colMapperImpl) MapSliceContainer(p0 SliceContainer) (SliceContainerDTO, error) {
	return map_SliceContainer_to_SliceContainerDTO(p0)
}
