// Code generated by graftgen; DO NOT EDIT.
// Source: UserMapper
package basic

// Helper: map_c2b1489071c3
func map_c2b1489071c3(in User) UserDTO {
	// Destination zero value; fields populated by node sequence below.
	var dst UserDTO
	dst.ID = in.ID
	dst.Name = in.Name
	return dst
}

// userMapperImpl is the generated implementation of UserMapper.
type userMapperImpl struct{}

// NewUserMapper returns a new UserMapper implementation.
func NewUserMapper() UserMapper { return &userMapperImpl{} }

// UserToDTO maps p0 to the destination type.
func (m *userMapperImpl) UserToDTO(p0 User) UserDTO {
	return map_c2b1489071c3(p0)
}
