// Code generated by graftgen (version devel); DO NOT EDIT.

// Source interfaces: UserMapper
// Command: graftgen -interface=UserMapper -output=graft_gen.go

package basic

// map_User_to_UserDTO maps a value of type User to UserDTO.
func map_User_to_UserDTO(in User) UserDTO {
	var dst UserDTO
	dst.ID = in.ID
	dst.Name = in.Name
	return dst
}

// userMapperImpl is the generated implementation of UserMapper.
type userMapperImpl struct{}

// NewUserMapper returns a new UserMapper implementation.
func NewUserMapper() UserMapper { return &userMapperImpl{} }

// UserToDTO maps p0 to the destination type.
func (m *userMapperImpl) UserToDTO(p0 User) UserDTO {
	return map_User_to_UserDTO(p0)
}
